platform :ios,’8.0‘

target 'jianshuDemo' do

 pod 'AFNetworking'

 pod 'Reachability'

 pod 'MJRefresh'

 pod 'SDWebImage'

 pod ’WebViewJavascriptBridge‘

 pod ’FDFullscreenPopGesture‘

 pod ’Masonry‘

 pod 'SDCycleScrollView'

 pod 'Realm’

 pod "DXPopover"

 pod 'React', :path => ‘./reactnative/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # 添加其他你想在工程中使用的依赖。
]

end
