platform :ios,’8.0‘

target 'jianshuDemo' do

 pod 'AFNetworking'

 pod 'Reachability'

 pod 'MJRefresh'

 pod 'SDWebImage'

 pod ’WebViewJavascriptBridge‘

 pod ’FDFullscreenPopGesture‘

 pod ’Masonry‘

 pod ‘FMDB’

 pod 'SDCycleScrollView'

 pod 'Realm'


end
