//
//  ReactNativeView.m
//  jianshuDemo
//
//  Created by quan on 16/8/8.
//  Copyright © 2016年 quan. All rights reserved.
//

#import "ReactNativeView.h"


@implementation ReactNativeView

- (instancetype)initWithFrame:(CGRect)frame
{
    if (self = [super initWithFrame:frame]) {
        
        NSDictionary *datas = @{@"dataSource": @[@"dsd", @"dfsfs", @"dgfh"]};
        
        NSString * strUrl = @"http://localhost:8081/index.ios.bundle?platform=ios&dev=true";
        NSURL * jsCodeLocation = [NSURL URLWithString:strUrl];
        
        // For production use, this `NSURL` could instead point to a pre-bundled file on disk:
        //
        //   NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
        //
        // generated by "Bundle React Native code and images" build step.
        //
        //   curl http://localhost:8081/index.ios.bundle -o main.jsbundle
        
        _rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                             moduleName:@"SimpleApp"
                                                      initialProperties:datas
                                                          launchOptions:nil];
        
        [self addSubview:_rootView];
        
        _rootView.frame = self.bounds;
    }
    return self;
}

@end
